import "@/styles/globals.css";
import type { Metadata } from "next";
import { Inter, Josefin_Sans } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });
const jos = Josefin_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Sail demo",
  description: "Generated by nacer",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${jos.className} h-screen w-screen`}>{children}</body>
    </html>
  );
}
